# Generated by Django 3.2.9 on 2021-12-04 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(help_text='User ID', max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='User Password', max_length=20)),
                ('name', models.CharField(help_text='Founder Name', max_length=20)),
                ('phone_number', models.CharField(help_text='phone number', max_length=12)),
                ('mail', models.CharField(help_text='E-Mail', max_length=20)),
                ('information', models.TextField(help_text='User Introduction')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryOwner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.user')),
                ('company_name', models.CharField(help_text='company Name', max_length=20)),
                ('address', models.CharField(help_text='address', max_length=50)),
                ('category', models.CharField(blank=True, help_text='category of factory sales', max_length=10)),
            ],
            bases=('app.user',),
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.user')),
                ('corporate_name', models.CharField(help_text='corporate Name', max_length=20)),
            ],
            bases=('app.user',),
        ),
        migrations.CreateModel(
            name='KeywordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='keyword for recommandation', max_length=20)),
                ('job', models.CharField(help_text='FactoryOwner or Founder', max_length=10)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='FounderEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='estimate title', max_length=30)),
                ('item_name', models.CharField(help_text='item name', max_length=20)),
                ('category', models.CharField(help_text='item category', max_length=20)),
                ('item_quantity', models.IntegerField(help_text='item order quantity')),
                ('date', models.DateField(auto_now_add=True, help_text='upload date')),
                ('keyword', models.CharField(help_text='keyword for recommandation', max_length=20)),
                ('content', models.TextField(help_text='Informations of factory')),
                ('founder_id', models.ForeignKey(db_column='founder_id', on_delete=django.db.models.deletion.CASCADE, related_name='founder', to='app.founder')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='estimate title', max_length=30)),
                ('content', models.TextField(help_text='Informations of factory')),
                ('date', models.DateField(auto_now_add=True, help_text='upload date')),
                ('keyword', models.CharField(help_text='keyword for recommandation', max_length=20)),
                ('factoryowner_id', models.ForeignKey(db_column='factoryowner_id', on_delete=django.db.models.deletion.CASCADE, related_name='factoryowner', to='app.factoryowner')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='start date')),
                ('end_date', models.DateField(help_text='end date')),
                ('factoryOwner', models.ForeignKey(db_column='factoryOwner', on_delete=django.db.models.deletion.CASCADE, related_name='factory_owner_id', to='app.factoryowner')),
                ('founder', models.ForeignKey(db_column='founder', on_delete=django.db.models.deletion.CASCADE, related_name='founder_id', to='app.founder')),
            ],
        ),
    ]
