# Generated by Django 3.2.9 on 2021-11-27 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory_Introd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Write title...', max_length=200)),
                ('contents', models.TextField(help_text='Write contents...')),
                ('factory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory', to='app.factory')),
            ],
        ),
        migrations.CreateModel(
            name='Founder_Est',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Write title...', max_length=200)),
                ('contents', models.TextField(help_text='Write contents...')),
                ('founder_id', models.ForeignKey(db_column='founder_id', on_delete=django.db.models.deletion.CASCADE, related_name='founder', to='app.founder')),
            ],
        ),
        migrations.RemoveField(
            model_name='founderest',
            name='founder_id',
        ),
        migrations.DeleteModel(
            name='FactoryItrod',
        ),
        migrations.DeleteModel(
            name='FounderEst',
        ),
    ]
