# Generated by Django 3.2.9 on 2021-11-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211128_0159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Factory_Introd',
            new_name='FactoryIntrod',
        ),
        migrations.RenameModel(
            old_name='Founder_Est',
            new_name='FounderEst',
        ),
    ]
