# Generated by Django 3.2.9 on 2021-11-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211128_0225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FactoryIntrod',
            new_name='Factory_Introd',
        ),
        migrations.RenameModel(
            old_name='FounderEst',
            new_name='Founder_Est',
        ),
    ]
